### ISSUE TITLE
What kind of scraping config for prometheus

### ISSUE THREAD

**Issue by PhilippeAccorsi** [danihodovic/borg-exporter#64]
Hi,
I have set this kind of scraping and prometheus can show metric.
```
  - job_name: 'borgbackup-metric'
    scrape_interval: 30m
    scrape_timeout: 1m
    static_configs:
      - targets: ['****:9996']
```
But I can't explore metric with prometheus graph view and not find value in grafana also.

Do you have any idea?

Regards,

I can see this king of result from my prometheus server if I open metric page `http://****:9996/metrics`
```
# HELP borg_backups_total Total number of Borg backups
# TYPE borg_backups_total gauge
borg_backups_total{repo="ssh://****:122/backup/borgbackup-repository"} 39.0
# HELP borg_last_backup_timestamp Timestamp of the last backup
# TYPE borg_last_backup_timestamp gauge
borg_last_backup_timestamp{repo="ssh://****:122/backup/borgbackup-repository"} 1.708938139e+09
# HELP borg_unique_size Uncompressed unique size of the Borg Repo
# TYPE borg_unique_size gauge
borg_unique_size{repo="ssh://****:122/backup/borgbackup-repository"} 9.36144236579e+011
```
